apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-nats-connector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-nats-connector
  template:
    metadata:
      labels:
        app: mongodb-nats-connector
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: mongodb-nats-connector
          image: mongodb-nats-connector
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/test?replicaSet=tilt&directConnection=true"
            - name: MONGO_WATCH_COLLECTIONS
              value: "users,movies"
            - name: NATS_SERVER_URL
              value: "nats://nats:4222"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nats-connector
  labels:
    app: mongodb-nats-connector
spec:
  clusterIP: None
  selector:
    app: mongodb-nats-connector
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: mongodb-nats-connector-port
