apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongodb
    spec:
      volumes:
        - name: mongo-config-volume
          configMap:
            name: init-replica-set
            items:
              - key: init-replica-set
                path: init-replica-set.js
      containers:
        - name: mongodb
          image: mongo:7.0.1
          ports:
            - containerPort: 27017
          args: ["--replSet", "tilt"]
          volumeMounts:
            - name: mongo-config-volume
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 15

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongo-port

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-replica-set
data:
  init-replica-set: |
    rs.initiate();
