version: 1

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - linux
    main: ./cmd/connector
    binary: mongodb-nats-connector

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}{{ if eq .Arch "arm" }}v{{ .Arm }}l{{ end }}
    files:
      - LICENSE.md
      - README.md

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  use: github

dockers:
  - id: arm image
    goos: linux
    goarch: arm
    use: buildx
    image_templates:
      - "mkramb/mongodb-nats-connector:latest-arm"
      - "mkramb/mongodb-nats-connector:{{ .Tag }}-arm"
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm"
